# Generated by Django 5.2.15 on 2026-07-14 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('idkor', models.AutoField(db_column='IDKor', primary_key=True, serialize=False)),
                ('korisnickoime', models.CharField(db_column='KorisnickoIme', max_length=30)),
                ('lozinka', models.CharField(db_column='Lozinka', max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('tip', models.IntegerField(db_column='Tip')),
                ('ime', models.CharField(db_column='Ime', max_length=20)),
                ('prezime', models.CharField(db_column='Prezime', max_length=20)),
                ('datumizmene', models.DateTimeField(blank=True, db_column='DatumIzmene', null=True)),
                ('obrisan', models.IntegerField(blank=True, db_column='Obrisan', null=True)),
                ('privatnost', models.IntegerField(db_column='Privatnost')),
                ('promenio', models.ForeignKey(blank=True, db_column='Promenio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tabletop.korisnik')),
            ],
            options={
                'db_table': 'korisnik',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Igra',
            fields=[
                ('idigre', models.AutoField(db_column='IDIgre', primary_key=True, serialize=False)),
                ('naziv', models.CharField(db_column='Naziv', max_length=100)),
                ('godinaproizvodnje', models.DateTimeField(db_column='GodinaProizvodnje')),
                ('minigraca', models.IntegerField(db_column='minIgraca')),
                ('maxigraca', models.IntegerField(db_column='maxIgraca')),
                ('opis', models.CharField(db_column='Opis', max_length=100)),
                ('slikaurl', models.CharField(db_column='slikaURL', max_length=255)),
                ('videotutorialurl', models.CharField(db_column='videoTutorialURL', max_length=255)),
                ('datumizmene', models.DateTimeField(blank=True, db_column='DatumIzmene', null=True)),
                ('obrisan', models.IntegerField(blank=True, db_column='Obrisan', null=True)),
                ('zanr', models.CharField(blank=True, db_column='Zanr', max_length=30, null=True)),
                ('promenio', models.ForeignKey(blank=True, db_column='Promenio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tabletop.korisnik')),
            ],
            options={
                'db_table': 'igra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Listaigara',
            fields=[
                ('pk', models.CompositePrimaryKey('idliste', 'idkor', blank=True, editable=False, primary_key=True, serialize=False)),
                ('idliste', models.IntegerField(db_column='IDListe')),
                ('nazivliste', models.CharField(db_column='NazivListe', max_length=30)),
                ('privatnost', models.IntegerField(db_column='Privatnost')),
                ('idigre', models.ForeignKey(db_column='IDIgre', on_delete=django.db.models.deletion.DO_NOTHING, to='tabletop.igra')),
                ('idkor', models.ForeignKey(db_column='IDKor', on_delete=django.db.models.deletion.DO_NOTHING, to='tabletop.korisnik')),
            ],
            options={
                'db_table': 'listaigara',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('pk', models.CompositePrimaryKey('idsta', 'idigre', blank=True, editable=False, primary_key=True,serialize=False)),
                ('idsta', models.IntegerField(db_column='IDSta')),
                ('idigre', models.ForeignKey(to='tabletop.igra', on_delete=django.db.models.DO_NOTHING, db_column='IDIgre')),
                ('datumkreiranja', models.DateTimeField(blank=True, db_column='DatumKreiranja', null=True)),
                ('kreirao', models.ForeignKey(to='tabletop.korisnik', on_delete=django.db.models.DO_NOTHING, db_column='Kreirao',blank=True, null=True)),
                ('naziv', models.CharField(db_column='Naziv', max_length=50)),
                ('tip', models.CharField(db_column='Tip', max_length=30)),
                ('opis', models.CharField(blank=True, db_column='Opis', max_length=20, null=True)),
                ('dropdown', models.CharField(blank=True, db_column='DropDown', max_length=200, null=True)),
                ('tipgrafikona', models.CharField(blank=True, db_column='TipGrafikona', max_length=20, null=True)),
                ('minvrednost', models.FloatField(blank=True, db_column='minVrednost', null=True)),
                ('maxvrednost', models.FloatField(blank=True, db_column='maxVrednost', null=True)),
                ('jedinicamere', models.CharField(blank=True, db_column='jedinicaMere', max_length=50, null=True)),
                ('maxduzinateksta', models.IntegerField(blank=True, db_column='maxDuzinaTeksta', null=True)),
                ('placeholdertekst',
                 models.CharField(blank=True, db_column='placeholderTekst', max_length=255, null=True)),
                ('podrazumevanavrednost',
                 models.CharField(blank=True, db_column='podrazumevanaVrednost', max_length=3, null=True)),
            ],
            options={
                'db_table': 'statistika',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prijatelji',
            fields=[
                ('pk', models.CompositePrimaryKey('idkor2', 'idkor1', blank=True, editable=False, primary_key=True, serialize=False)),
                ('statuszahteva', models.IntegerField(db_column='statusZahteva')),
                ('idkor1', models.ForeignKey(db_column='IDKor1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='prijatelji_idkor1_set', to='tabletop.korisnik')),
                ('idkor2', models.ForeignKey(db_column='IDKor2', on_delete=django.db.models.deletion.DO_NOTHING, to='tabletop.korisnik')),
            ],
            options={
                'db_table': 'prijatelji',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vodjenastatistika',
            fields=[
                ('vrednost', models.CharField(db_column='Vrednost', max_length=100)),
                ('datum', models.DateTimeField(db_column='Datum')),
                ('tekst', models.CharField(blank=True, db_column='Tekst', max_length=30, null=True)),
                ('idvodj', models.AutoField(db_column='IDVodj', primary_key=True, serialize=False)),
                ('idigre', models.IntegerField()),
                ('idsta', models.IntegerField()),
                ('privatnost', models.IntegerField(db_column='Privatnost')),
                ('idkor', models.ForeignKey(blank=True, db_column='IDKor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tabletop.korisnik')),
                ('statistic', models.ForeignObject(from_fields=('idsta', 'idigre'), on_delete=django.db.models.deletion.DO_NOTHING, to='tabletop.statistika', to_fields=('idsta', 'idigre'))),
            ],
            options={
                'db_table': 'vodjenastatistika',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dostignuca',
            fields=[
                ('vrednostzadostici', models.CharField(db_column='VrednostZaDostici', max_length=40)),
                ('naziv', models.CharField(db_column='Naziv', max_length=20)),
                ('uslov', models.CharField(blank=True, db_column='Uslov', max_length=20, null=True)),
                ('datumkreiranja', models.DateTimeField(blank=True, db_column='DatumKreiranja', null=True)),
                ('slikaurl', models.CharField(blank=True, db_column='slikaURL', max_length=255, null=True)),
                ('iddos', models.AutoField(db_column='IDDos', primary_key=True, serialize=False)),
                ('idigre', models.IntegerField()),
                ('idsta', models.IntegerField()),
                ('opis', models.CharField(blank=True, db_column='Opis', max_length=255, null=True)),
                ('kreirao', models.ForeignKey(blank=True, db_column='Kreirao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tabletop.korisnik')),
                ('statistic', models.ForeignObject(from_fields=('idsta', 'idigre'), on_delete=django.db.models.deletion.DO_NOTHING, to='tabletop.statistika', to_fields=('idsta', 'idigre'))),
            ],
            options={
                'db_table': 'dostignuca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Utisak',
            fields=[
                ('pk', models.CompositePrimaryKey('idigre', 'idkor', blank=True, editable=False, primary_key=True, serialize=False)),
                ('opis', models.CharField(db_column='Opis', max_length=300)),
                ('ocena', models.IntegerField(db_column='Ocena')),
                ('datumizmene', models.DateTimeField(blank=True, db_column='DatumIzmene', null=True)),
                ('razlogizmene', models.CharField(blank=True, db_column='RazlogIzmene', max_length=50, null=True)),
                ('statusizmene', models.IntegerField(blank=True, db_column='StatusIzmene', null=True)),
                ('originalniopis', models.CharField(blank=True, db_column='OriginalniOpis', max_length=300, null=True)),
                ('idigre', models.ForeignKey(db_column='IDIgre', on_delete=django.db.models.deletion.DO_NOTHING, to='tabletop.igra')),
                ('idkor', models.ForeignKey(db_column='IDKor', on_delete=django.db.models.deletion.DO_NOTHING, to='tabletop.korisnik')),
                ('promenio', models.ForeignKey(blank=True, db_column='Promenio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='utisak_promenio_set', to='tabletop.korisnik')),
            ],
            options={
                'db_table': 'utisak',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Korisnikdostignuca',
            fields=[
                ('datum', models.DateTimeField(db_column='Datum')),
                ('idvodj', models.OneToOneField(db_column='IDVodj', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tabletop.vodjenastatistika')),
                ('privatnost', models.IntegerField(db_column='privatnost')),
                ('dostignuce', models.ForeignKey(db_column='dostignuce', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='tabletop.dostignuca')),
            ],
            options={
                'db_table': 'korisnikdostignuca',
                'managed': True,
            },
        ),
    ]
